# Generated by Django 5.2 on 2025-05-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('membre', 'date')},
        ),
    ]
