# Generated by Django 5.2 on 2025-05-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_presence_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moniteur', 'Moniteur'), ('gest_rencontre', 'Gestion Rencontre'), ('admin', 'Super Admin')], max_length=20),
        ),
    ]
