# Generated by Django 5.2 on 2025-05-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_mediagallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='slides/')),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
