# Generated by Django 5.2 on 2025-05-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_published', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('evenement', 'Événement'), ('communique', 'Communiqué'), ('annonce', 'Annonce')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='slide',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
    ]
