# Generated by Django 5.2 on 2025-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_annonce_slide_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='annonces/'),
        ),
    ]
