# Generated by Django 5.2 on 2025-05-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0005_annonce_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='programmes/')),
                ('date', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
