# Generated by Django 5.2 on 2025-05-06 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0006_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('couverture', models.ImageField(upload_to='galeries/couvertures/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galeries/images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('galerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vitrine.galerie')),
            ],
        ),
    ]
