# Generated by Django 5.2 on 2025-05-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0007_galerie_imagegalerie'),
    ]

    operations = [
        migrations.CreateModel(
            name='RencontreQuotidienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('text_biblique', models.TextField()),
                ('message', models.TextField()),
                ('apercu', models.TextField()),
                ('application', models.TextField()),
                ('prieres', models.TextField()),
                ('lecture_biblique_annuelle', models.TextField()),
            ],
            options={
                'verbose_name': 'Rencontre quotidienne',
                'verbose_name_plural': 'Rencontres quotidiennes',
                'ordering': ['-date'],
            },
        ),
    ]
